import java.util.HashMap;
import java.util.Map;

public class Awards {
	private static String[] jmenaDBLP_Codd = { "E. F. CODD", "MICHAEL STONEBRAKER",
			"JIM GRAY", "PHILIP A. BERNSTEIN", "DAVID J. DEWITT", "C. MOHAN",
			"DAVID MAIER", "SERGE ABITEBOUL", "HECTOR GARCIA-MOLINA",
			"RAKESH AGRAWAL", "RUDOLF BAYER", "PATRICIA G. SELINGER",
			"DONALD D. CHAMBERLIN", "RONALD FAGIN", "MICHAEL J. CAREY",
			"JEFFREY D. ULLMAN", "JENNIFER WIDOM", "MOSHE Y. VARDI",
			"MASARU KITSUREGAWA", "UMESHWAR DAYAL" };
	// CiteSeer
	private static String[] jmenaCiteSeer_Codd = { "E. F. CODD", "MICHAEL STONEBRAKER",
			"JIM GRAY", "PHILIP A. BERNSTEIN", "DAVID J. DEWITT", "C. MOHAN",
			"DAVID MAIER", "SERGE ABITEBOUL", "HECTOR GARCIA-MOLINA",
			"RAKESH AGRAWAL", "RUDOLF BAYER", "PATRICIA G. SELINGER",
			"DON CHAMBERLIN", "RONALD FAGIN", "MICHAEL J. CAREY",
			"JEFFREY D. ULLMAN", "JENNIFER WIDOM", "MOSHE Y. VARDI",
			"MASARU KITSUREGAWA", "UMESHWAR DAYAL" };

	// ACM Fellows
	// DBLP
	private static String[] jmenaDBLP_ACMFell = { "SERGE ABITEBOUL", "W. RICHARDS ADRION",
			"SARITA V. ADVE", "ALFRED V. AHO", "IAN F. AKYILDIZ",
			"RAJEEV ALUR", "ANDREW W. APPEL", "HAGIT ATTIYA",
			"OUMLZALP BABAOGLU", "LUIZ ANDREACUTE BARROSO", "VICTOR R. BASILI",
			"KENNETH E. BATCHER", "CATRIEL BEERI", "HAL BERGHEL",
			"ELISA BERTINO", "LAXMI N. BHUYAN", "KENNETH P. BIRMAN",
			"JOSEACUTE A. BLAKELEY", "GUY E. BLELLOCH", "SHAHID H. BOKHARI",
			"GRADY BOOCH", "RONALD J. BRACHMAN", "YURI BREITBART",
			"JANIS A. BUBENKO JR.", "PETER BUNEMAN", "STUART K. CARD",
			"LUCA CARDELLI", "DONALD D. CHAMBERLIN", "BERNARD CHAZELLE",
			"IMRICH CHLAMTAC", "KENNETH L. CLARKSON", "J. DANIEL COUGER",
			"MARK CROVELLA", "MICHAEL DAHLIN", "THOMAS A. DEFANTI",
			"RICHARD A. DEMILLO", "DAVID J. DEWITT", "DAVID P. DOBKIN",
			"DANNY DOLEV", "JACK DONGARRA", "RONALD FAGIN",
			"RICHARD J. FATEMAN", "JOAN FEIGENBAUM", "MATTHIAS FELLEISEN",
			"JEANNE FERRANTE", "KENNETH D. FORBUS", "GEORGE W. FURNAS",
			"HAROLD N. GABOW", "M. R. GAREY", "JONATHAN GIBBONS",
			"DAVID K. GIFFORD", "LEO R. GOTLIEB", "LEONIDAS J. GUIBAS",
			"JOHN V. GUTTAG", "DONALD J. HADERLE", "BRENT HAILPERN",
			"JOSEPH Y. HALPERN", "JURIS HARTMANIS", "DAVID HECKERMAN",
			"PHILIP HEIDELBERGER", "MONIKA RAUCH HENZINGER", "MAURICE HERLIHY",
			"W. DANIEL HILLIS", "JOHN E. HOPCROFT", "RICHARD HULL",
			"TOSHIHIDE IBARAKI", "OSCAR H. IBARRA", "NEIL IMMERMAN",
			"H. V. JAGADISH", "FARNAM JAHANIAN", "M. FRANS KAASHOEK",
			"TAKEO KANADE", "HOWARD J. KARLOFF", "ZVI M. KEDEM",
			"CHARLES KELLOGG", "RICHARD B. KIEBURTZ", "JAMES E. KIRKPATRICK",
			"MARIA M. KLAWE", "JON C. KLENSIN", "PHOKION G. KOLAITIS",
			"JOSEPH A. KONSTAN", "HENRY F. KORTH", "S. RAO KOSARAJU",
			"DEXTER KOZEN", "DAVID J. KUCK", "JAMES F. KUROSE",
			"RICHARD E. LADNER", "S. LAKSHMIVARAHAN", "AXEL VAN LAMSWEERDE",
			"JAMES R. LARUS", "JOHN LAUNCHBURY", "STEPHEN S. LAVENBERG",
			"JOSHUA LEDERBERG", "CHARLES E. LEISERSON", "MAURIZIO LENZERINI",
			"NANCY G. LEVESON", "MARC LEVOY", "BARBARA LISKOV",
			"WITOLD LITWIN", "DAVID B. LOMET", "DONALD W. LOVELAND",
			"DAVID B. MACQUEEN", "DAHLIA MALKHI", "ZOHAR MANNA",
			"MARGARET MARTONOSI", "LARRY MASINTER", "PAUL R. MCJONES",
			"KURT MEHLHORN", "JEFFREY C. MOGUL", "RAJEEV MOTWANI",
			"ALICE H. MUNTZ", "RICHARD E. NANCE", "TAKAO NISHIZEKI",
			"PETER NORVIG", "DAVID NOTKIN", "MARTIN ODERSKY",
			"LEON J. OSTERWEIL", "JOHN K. OUSTERHOUT", "SUSAN S. OWICKI",
			"JAACUTENOS PACH", "DAVID A. PADUA", "KRISHNA V. PALEM",
			"CHERRI M. PANCAKE", "RANDY F. PAUSCH", "CAROLINE PAXSON",
			"NICHOLAS PIPPENGER", "HAMID PIRAHESH", "FRANCO P. PREPARATA",
			"KRITHI RAMAMRITHAM", "DAVID A. RANDELL", "JOHN H. REIF",
			"THOMAS W. REPS", "ARISTIDES A. G. REQUICHA", "MARTIN C. RINARD",
			"KRISHAN K. SABNANI", "DAVID SALESIN", "GERARD SALTON",
			"JEAN E. SAMMET", "RAVI S. SANDHU", "HANS-JOUMLRG SCHEK",
			"RICHARD D. SCHLICHTING", "ROBERT SEDGEWICK",
			"PATRICIA G. SELINGER", "BART SELMAN", "MARGO I. SELTZER",
			"KENNETH C. SEVCIK", "MICHA SHARIR", "DAVID B. SHMOYS",
			"BEN SHNEIDERMAN", "DANIEL P. SIEWIOREK", "MUKESH SINGHAL",
			"DONALD R. SLUTZ", "RICHARD T. SNODGRASS", "MARY LOU SOFFA",
			"EUGENE H. SPAFFORD", "ALFRED Z. SPECTOR", "KENNETH STEIGLITZ",
			"LARRY J. STOCKMEYER", "MICHAEL STONEBRAKER", "BJARNE STROUSTRUP",
			"GERALD J. SUSSMAN", "EACUTEVA TARDOS", "ROBERT ENDRE TARJAN",
			"MIKKEL THORUP", "MARTIN TOMPA", "JOSEP TORRELLAS",
			"IRVING L. TRAIGER", "ELI UPFAL", "MOSHE Y. VARDI",
			"VARGHESE S. JACOB", "VICTOR VIANU", "UZI VISHKIN",
			"JEFFREY SCOTT VITTER", "PHILIP WADLER", "DAVID L. WALTZ",
			"ROY WANT", "BEN WEGBREIT", "GERHARD WEIKUM", "ELAINE J. WEYUKER",
			"JENNIFER WIDOM", "ROBERT WILENSKY", "SHMUEL WINOGRAD",
			"MARIANNE WINSLETT", "DAVID S. WISE", "IAN H. WITTEN",
			"WILLIAM A. WULF", "MIHALIS YANNAKAKIS", "F. KENNETH ZADECK",
			"STANLEY B. ZDONIK", "ANDREAS ZELLER", "WILLY ZWAENEPOEL",
			"STUART H. ZWEBEN" };
	// CiteSeer
	private static String[] jmenaCiteSeer_ACMFell = { "MIGUEL ABADI", "S. ABITEBOUL",
			"GREGORY ABOWD", "W. RICHARDS ADRION", "SARITA ADVE ELECTRICAL",
			"ALFRED V. AHO", "NARENDRA AHUJA", "ERIC ALLENDER", "RAJEEV ALUR",
			"LORENZO ALVISI PH. D", "ANDREW W. APPEL", "MIKHAIL ATALLAH",
			"BRENTON ATCHISON", "HAGIT ATTIYA T", "LOUIS AUSLANDER",
			"RICHARD AUSTING", "ZALP BABAOGLU", "FRANCIS BACON",
			"AKHILESH BAJAJ", "RADIM S ARA RUZENA BAJCSY", "V. BASILI",
			"KENNETH BATCHER", "I. J. BATE", "CATRIEL BEERI", "ELISA BERTINO",
			"LAXMI N. BHUYAN", "OLIVER BIERMANN", "ANDERS BJORNER",
			"JOS'E A. BLAKELEY", "G. E. BLELLOCH", "ROBERT J. BOBROW",
			"GREGOR VON BOCHMANN", "PAUL T. BOGGS", "S. BORMAN",
			"GAETANO BORRIELLO", "PHILIP BOURNE", "RONALD J. BRACHMAN",
			"B. A. BRANDIN", "JANIS A. BUBENKO", "PETER BUNEMAN",
			"LUCA CARDELLI", "EDWIN CATMULL", "SIRISH CHANDRASEKARAN",
			"JENNIFER T. CHAYES", "BERNARD CHAZELLE", "COMER DUNCAN",
			"ANNE CONDON", "WILLIAM CROFT", "LIANG CROVELLA", "RON CYTRON",
			"WILLIAM J. DALLY", "BRUCE S. DAVIE", "UMESH DAYAL",
			"THOMAS A. DEFANTI", "JAMES W. DEMMEL", "DAVID J. DEWITT",
			"IHOMAS G. DIETTERICH", "DAVID DILL", "CHRISTOPHE DIOT Y",
			"D. DOLEV", "J DONGARRA", "WERNER EBELING", "L. MIGUEL ENCARNACAO",
			"DAVID EPPSTEIN", "DEBORAH ESTRIN", "RON FAGIN", "HENRY S. FARBER",
			"RICHARD J. FATEMAN", "J. FEIGENBAUM", "MATTHISS FELLEISEN",
			"KENNETH FORBUS", "LANCE J. FORTNOW", "HAROLD GABOW", "ZVI GALIL",
			"DENNIS GANNON", "M. R. GAREY", "PROF CARLO GHEZZI",
			"DAVID K. GIFFORD", "MATTHEW L. GINSBERG", "MICHEL GOEMANS",
			"M. T. GOODRICH", "ARNAUD GOTLIEB", "M. GOVINDARAJU",
			"W. D. GROPP", "L. GROSZ", "L. GUIBAS", "COMMUNICATED Y. GUREVICH",
			"JOHN V. GUTTAG", "BRENT HAILPERN", "JOSEPH HALPERN", "D. HAREL",
			"JURIS HARTMANIS", "J. P. HEARN", "D. HECKERMAN",
			"PHILIP HEIDELBERGER", "L. HENDREN", "DANIEL HENNESSY",
			"MONIKA R. HENZINGER", "MAURICE HERLIHY", "GERARD J. HOLZMANN",
			"JOHN E. HOPCROFT", "JAMES J. HORNING", "J. P. HUBAUX",
			"N. IMMERMAN", "FARNAM JAHANIAN PRAKASH", "JOSEPH JAJA",
			"WILLIAM KAHAN", "RICH KALTOFEN", "HOWARD KARLOFF",
			"LYDIA KAVRAKI T", "MARIA M. KLAWE", "D. E. KNUTH",
			"PHOKION G. KOLAITIS", "J DONALD KOSSMANN", "G. KRAUT",
			"H. -P. KRIEGEL", "RICHARD E. LADNER", "B. LAMPSON",
			"A. VAN LAMSWEERDE", "LAURA F. LANDWEBER", "J. LAUNCHBURY",
			"EDWARD LAZOWSKA", "GIACOMO MAURIZIO LENZERINI", "N. LEVESON",
			"MARC LEVOY", "R. LIPTON", "H. LISKOV", "TODD LITWIN",
			"DAVID LOMET", "P. GEOFFREY LOWNEY", "DAVID MACQUEEN",
			"PETER S MAGNUSSON", "ERIC MAISEL", "DINESH MANOCHA BILL GARRETT",
			"MARGARET MARTONOSI", "LARRY MASINTER", "EDWARD J. MCCLUSKEY",
			"PAUL MCJONES", "E. DE MICHELI", "RITA G. MINKER",
			"PAUL V. MOCKAPETRIS", "RAJEEV MOTWANI", "D. MUNTZ",
			"MOORTHY MUTHUKRISHNAN", "ROGER NEEDHAM", "JURG NIEVERGELT",
			"PETER NORVIG", "D. NOTKIN", "DIANNE P. O'LEARY", "MARTIN ODERSKY",
			"OYEKUNLE OLUKOTUN", "SUSAN OWICKI", "DAVID A. PADUA",
			"KRISHNA V. PALEM", "P. PAPADIMITRIOU", "L. PARNAS", "BOAZ PATT",
			"Y PAUSCH (DISSERTATION ADVISOR", "LINDA PETZOLD",
			"PAVEL A. PEVZNER", "HAMID PIRAHESH", "PROF AMIR PNUELI",
			"BRYAN PREAS", "FRANCO P. PREPARATA", "SAMUEL PULLEN",
			"RADA F. MIHALCEA", "KRITHI RAMAMRITHAM MEMBER", "B. RANDELL",
			"M. REINGOLD", "THOMAS REPS", "ARISTIDES A. G. REQUICHA",
			"JENNIFER L. REXFORD", "REINHARD RIEDL", "MARTIN C. RINARD",
			"MARK ROSENBLUM", "DANIEL ROSENKRANTZ", "KRISHAN K. SABNANI",
			"S. SAHNI", "DAVID SALESIN", "GERARD SALTON", "AMHED SAMEH",
			"LARRY SAMUELSON", "ANDERS B. SANDHOLM",
			"RAVINDERPAL SINGH SANDHU", "MAHADEV SATYANARAYANAN",
			"RICHARD D. SCHLICHTING", "JULIA A. SCHNABEL", "ROBERT SEDGEWICK",
			"CARLO H. SEQUIN", "M. SHARIR S", "SCOTT SHENKER (XEROX",
			"D. B. SHMOYS", "KUMAR PLAISANT SHNEIDERMAN", "R. K. SHYAMASUNDAR",
			"M. SNIR", "MARY LOU SOFFA", "DIANE L. SOUVAINE",
			"DANIEL SPIELMAN", "MARK S. SQUILLANTE", "JACK STANKOVIC",
			"RICHARD SQUIER STEIGLITZ", "ERIK S. STEINMETZ",
			"MICHAEL K. STENSTROM", "EDGARDO STOCKMEYER",
			"UBELL MICHAEL STONEBRAKER", "BJARNE STROUSTRUP", "ER I. SUCIU",
			"M. SUDAN", "RICHARD SZELISKI", "S. TUCKER TAFT",
			"A. S. TANENBAUM", "G. TARDOS", "D. TERZOPOULOS",
			"SANJEEV THACKER", "RAMOHAN A. THEKKATH", "MIKKEL THORUP",
			"MARTIN TOMPA", "KOJI TORII", "J. TRAUB", "DEAN M. TULLSEN",
			"ANNA R. KARLIN ELI UPFAL", "MATHER AMIN VAHDAT",
			"GEORGE VARGHESE", "V. VIANU", "UZI VISHKIN", "JEREY S. VITTER",
			"PHILIP WADLER AVAYA LABS", "M. P. WAND", "ROY WANT",
			"HENRY WASSERMAN", "BEN WEGBREIT", "EDWARD J. WEGMAN",
			"DANIEL S. WELD", "EMO WELZL", "ELAINE J. WEYUKER",
			"TURNER WHITTED", "PETER WIDMAYER", "BRENDA WIEDERHOLD",
			"M. WILKES", "ALLAN R. WILKS", "SHMUEL WINOGRAD",
			"KENT E. SEAMONS MARIANNE WINSLETT", "H. WITTEN", "M. YANNAKAKIS",
			"AKI YONEZAWA", "FROM PAMELA ZAVE", "B. ZDONIK" };

	// ISI Highly Cited
	// DBLP
	private static String[] jmenaDBLP_ISIHC = { "SERGE ABITEBOUL", "EDWARD H. ADELSON",
			"IAN F. AKYILDIZ", "RAJEEV ALUR", "KRZYSZTOF R. APT",
			"JACK J. BAROUDI", "TERENCE M. BARRON", "VICTOR R. BASILI",
			"CATRIEL BEERI", "JAN A. BERGSTRA", "LAXMI N. BHUYAN",
			"ANDREW BIRRELL", "SHAHID H. BOKHARI", "JEHOSHUA BRUCK",
			"JOHN CHANDY", "BERNARD CHAZELLE", "IMRICH CHLAMTAC",
			"KAREL CULIK II", "DANNY DOLEV", "JACK DONGARRA", "CYNTHIA DWORK",
			"DEREK L. EAGER", "HERBERT EDELSBRUNNER", "ANDRZEJ EHRENFEUCHT",
			"E. ALLEN EMERSON", "RONALD FAGIN", "JEANNE FERRANTE",
			"PHILIPPE FLAJOLET", "GREG N. FREDERICKSON", "HAROLD N. GABOW",
			"DAVID GELERNTER", "ODED GOLDREICH", "JUDY GOLDSMITH",
			"MICHAEL GOLDWASSER", "JOSEPH Y. HALPERN", "SVEN HAMMARLING",
			"DAVID HAUSSLER", "MONIKA RAUCH HENZINGER", "DORIT S. HOCHBAUM",
			"OSCAR H. IBARRA", "NEIL IMMERMAN", "THOMAS JOHNSSON",
			"TADAO KASAMI", "CHRIS F. KEMERER", "JAMES E. KIRKPATRICK",
			"JAN WILLEM KLOP", "DEXTER KOZEN", "LESLIE LAMPORT",
			"WENDY G. LEHNERT", "NANCY G. LEVESON", "MARC LEVOY",
			"NATHAN LINIAL", "BARBARA LISKOV", "UDI MANBER", "NIMROD MEGIDDO",
			"KURT MEHLHORN", "DAVID NASSIMI", "MARK H. OVERMARS",
			"CAROLINE PAXSON", "HENRI PRADE", "FRANCO P. PREPARATA",
			"CHARLES RACKOFF", "KRITHI RAMAMRITHAM", "JOHN H. REIF",
			"THOMAS W. REPS", "ARISTIDES A. G. REQUICHA", "JORMA RISSANEN",
			"WALTER L. RUZZO", "GERARD SALTON", "ROBERT E. SCHAPIRE",
			"KENNETH C. SEVCIK", "MICHA SHARIR", "YOSSI SHILOACH",
			"BEN SHNEIDERMAN", "PETER W. SHOR", "DANIEL DOMINIC SLEATOR",
			"LARRY J. STOCKMEYER", "JORGE STOLFI", "ROBERTO TAMASSIA",
			"ROBERT ENDRE TARJAN", "SAM TOUEG", "LESLIE G. VALIANT",
			"MOSHE Y. VARDI", "UZI VISHKIN", "JEFFREY SCOTT VITTER",
			"JEAN VUILLEMIN", "ELAINE J. WEYUKER", "AVI WIGDERSON",
			"IAN H. WITTEN", "MIHALIS YANNAKAKIS", "JOHN ZAHORJAN" };
	// CiteSeer
	private static String[] jmenaCiteSeer_ISIHC = { "B. AAZHANG", "MIGUEL ABADI",
			"S. ABITEBOUL", "J. ADELSON", "M. AHMADI", "MOHAMED-SLIM ALOUINI",
			"RAJEEV ALUR", "MIKHAIL ATALLAH", "TOR M. AULIN", "G. BALBO",
			"ANDREW R. BARRON", "V. BASILI", "CATRIEL BEERI",
			"JAN A. BERGSTRA", "LAXMI N. BHUYAN", "E. BIGLIERI",
			"HANS L. BODLAENDER T", "ROBERT C. BOLLES", "GILLES BRASSARD",
			"MANFRED BROY", "JEHOSHUA BRUCK", "DAVID M. J. CALDERBANK",
			"BERNARD CHAZELLE", "DAVID CHERITON", "JOHN G. CLEARY",
			"DON COPPERSMITH", "B. COURCELLE", "WILLIAM CROFT",
			"JEREMY DU CROZ", "KAREL CULIK II", "WILLIAM J. DALLY",
			"INGRID DAUBECHIES", "DAVID DILL", "DARIUSH DIVSALAR", "D. DOLEV",
			"J DONGARRA", "ES DAVID L. DONOHO", "DAVID DUFF", "DEREK EAGER",
			"READER HERBERT EDELSBRUNNER", "JOERI ENGELFRIET", "RON FAGIN",
			"N. FARVARDIN", "P. FLAJOLET", "G. J. FOSCHINI",
			"FOSSORIER ZIXIANG", "M. L. FREDMAN", "HAROLD GABOW", "ZVI GALIL",
			"R. GALLAGER", "DAVID GELERNTER", "SHA GOLDWASSER",
			"BENJAMIN GREENSTEIN", "JOACHIM HAGENAUER", "JOSEPH HALPERN",
			"SVEN J. HAMMARLING", "D. HAREL", "BABAK HASSIBI",
			"DANIEL HENNESSY", "MONIKA R. HENZINGER", "MICHAEL G. HLUCHYJ",
			"DORIT S. HOCHBAUM", "BERTRAND HOCHWALD SWELDENS", "N. IMMERMAN",
			"HAMID JAFARKHANI", "THOMAS KAILATH", "EDWARD J. KANSA",
			"N. KARMARKAR", "CHRIS F. KEMERER", "ALEX KRUSKAL",
			"J. NICHOLAS LANEMAN", "EDWARD LAZOWSKA", "WENDY G. LEHNERT",
			"KHALED BEN LETAIEF", "N. LEVESON", "D. LEVIATAN", "MARC LEVOY",
			"N. LINIAL", "H. LISKOV", "MICHAEL LUBY", "DAVID M. LUCANTONI",
			"UPAMANYU MADHOW", "ST EPHANE MALLAT", "DIRECTOR UDI MANBER",
			"LAURENT MARSAN", "N. F. MAXEMCHUK", "ROBERT MCELIECE",
			"NIMROD MEGIDDO", "NERI MERHAV T", "SILVIO MICALI", "SUVO MITTRA",
			"N. MOENECLAEY", "GUIDO MONTORSI", "M. NAGHSHINEH",
			"DAVID NASSIMI", "M. H. OVERMARS", "P. PAPADIMITRIOU",
			"JOACHIM PARROW", "AROGYSWAMI PAULRAJ", "PROF AMIR PNUELI",
			"ANDREAS POLYDOROS", "FRANCO P. PREPARATA", "CHARLES RACKOFF",
			"RAGHAVENDRA DONAMUKKALA", "KRITHI RAMAMRITHAM MEMBER",
			"SUNEETA RAMASWAMI", "D. RAYCHAUDHURI", "THOMAS REPS",
			"ARISTIDES A. G. REQUICHA", "ROSCOE GILES", "RUZZO W. L",
			"S. SAHNI", "GERARD SALTON", "TALYA SALZ", "MAMORU SAWAHASHI",
			"R. SCHAPIRE", "DANIEL H. SCHAUBERT", "SHLOMO SHAMAI (SHITZ",
			"M. SHARIR S", "KUMAR PLAISANT SHNEIDERMAN", "PETER W. SHOR",
			"SISTLA CLEMENT YU", "TYCHO SLEATOR", "M. SNIR", "SOLOWAY EHRHCH",
			"JACK STANKOVIC", "EDGARDO STOCKMEYER", "JORGE STOLFI",
			"ESWARAN SUBRAHMANIAN", "M. SUDAN", "GIORGIO TARICCO",
			"VAHID TAROKH", "T. TEITELBAUM", "ER VARDY", "UZI VISHKIN",
			"ANDREW J VITERBI", "EMANUELE VITERBO", "JEREY S. VITTER",
			"JEAN E. VUILLEMIN", "MANFRED WARMUTH", "B. WELSCH",
			"ELAINE J. WEYUKER", "STEVEN WILTON", "H. WITTEN", "M. YANNAKAKIS",
			"JOHN ZAHORJAN" };

	// ACM Turing Award
	// DBLP
	private static String[] jmenaDBLP_Turing = { "LEONARD M. ADLEMAN", "JOHN COCKE",
			"E. ALLEN EMERSON", "JOAN FEIGENBAUM", "JURIS HARTMANIS",
			"JOHN E. HOPCROFT", "BARBARA LISKOV", "PETER NAUR",
			"DONALD PERLIS", "JOSEPH SIFAKIS", "ROBERT ENDRE TARJAN",
			"LESLIE G. VALIANT" };
	// CiteSeer
	private static String[] jmenaCiteSeer_Turing = { "M. ADLEMAN", "C. R. BACHMAN",
			"BENJAMIN T. BACKUS", "JOHN COCKE STEPHEN", "J. FEIGENBAUM",
			"JURIS HARTMANIS", "JOHN E. HOPCROFT", "WILLIAM KAHAN",
			"D. E. KNUTH", "B. LAMPSON", "H. LISKOV", "ERLING NYGAARD",
			"PROF AMIR PNUELI", "DAN RABIN", "SANJEEV THACKER", "M. WILKES" };

	public static boolean[] assignAwards(ResultRow[] result, String db, String award) {
		String[] names = null;
		
		if ("DBLP".equals(db)) {
			if ("Codd".equals(award))
				names = jmenaDBLP_Codd;
			else if ("ACMFell".equals(award))
				names = jmenaDBLP_ACMFell;
			else if ("ISIHC".equals(award))
				names = jmenaDBLP_ISIHC;
			else if ("Turing".equals(award))
				names = jmenaDBLP_Turing;
		} else if ("CiteSeer".equals(db)) {
			if ("Codd".equals(award))
				names = jmenaCiteSeer_Codd;
			else if ("ACMFell".equals(award))
				names = jmenaCiteSeer_ACMFell;
			else if ("ISIHC".equals(award))
				names = jmenaCiteSeer_ISIHC;
			else if ("Turing".equals(award))
				names = jmenaCiteSeer_Turing;
		}
		
		if (names == null)
			return null;
		
		Map<String, Boolean> exists = new HashMap<String, Boolean>();
		for (String name : names)
			exists.put(name,  true);
		
		boolean[] awarded = new boolean[result.length];
		for (int i = 0; i < result.length; i++)
			awarded[i] = exists.containsKey(result[i].name);
		
		return awarded;
	}
	
	public static int getSum(boolean[] awarded) {
		int sum = 0;
		
		if (awarded == null)
			return sum;
		
		for (int i = 0; i < awarded.length; i++)
			if (awarded[i])
				sum += i;
		
		return sum;
	}
}